# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        OS: [linux-x64, win-x64]
        SELF_CONTAINED: [true, false]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - uses: actions/cache@v6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build ${{matrix.OS}}${{matrix.SELF_CONTAINED && ' self-contained'}}
        run: dotnet publish -r ${{matrix.OS}} --self-contained=${{matrix.SELF_CONTAINED}} /p:PublishSingleFile=true
      - name: Rename self-contained file
        if: ${{ matrix.SELF_CONTAINED == true }}
        run: mv ./bin/Release/net10.0/${{matrix.OS}}/publish/ZapretUpdater${{matrix.OS == 'win-x64' && '.exe' || ''}} ./bin/Release/net10.0/${{matrix.OS}}/publish/ZapretUpdater-Contained${{matrix.OS == 'win-x64' && '.exe' || ''}}
      - name: Upload release artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-${{matrix.SELF_CONTAINED}}${{matrix.SELF_CONTAINED == true && '-contained' || ''}}
          path: bin/Release/net10.0/${{matrix.OS}}/publish/ZapretUpdater**

  release:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: build-*
          merge-multiple: true
          path: artifacts
      - name: Create GitHub Release
        run: gh release create "build-${{ github.run_id }}" artifacts/* --generate-notes -R ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
