# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x
    - name: Test
      run: dotnet run -- -p -s
    - name: Build Windows
      run: dotnet publish -r win-x64 --self-contained=false --no-restore /p:PublishSingleFile=true
    - name: Build Linux
      run: dotnet publish -r linux-x64 --self-contained=false --no-restore /p:PublishSingleFile=true
    - name: Creating release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: "beta"
        prerelease: "true"
        files: |
          ./bin/Release/net10.0/*/publish/ZapretUpdater*
        generate_release_notes: "true"
        
